name: Build

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [x86_64, i686]
        win32_winnt: ['0x0601', '0x0502', '0x0500']
        exclude:
        - arch: x86_64
          win32_winnt: '0x0500'
        - arch: i686
          win32_winnt: '0x0502'

    steps:
      - uses: actions/checkout@v4

      - uses: msys2/setup-msys2@v2
        with:
          update: true

      - name: Build
        shell: msys2 {0}
        run: |
          common_args=" \
            --buildroot=/c/buildroot \
            --jobs=4 \
            --logviewer-command=cat \
            --mode=gcc-11.5.0 \
            --enable-languages=c,c++ \
            --arch=${{ matrix.arch }} \
            --exceptions=dwarfseh \
            --threads=posix \
            --rt-version=v9 \
            --with-default-win32-winnt=${{ matrix.win32_winnt }} \
            --rev=1"
          ./build $common_args --fetch-only
          ./build $common_args --bin-compress

      - name: Rename Windows 7 builds
        shell: msys2 {0}
        run: |
          if [[ ${{ matrix.win32_winnt }} -eq 0x0601 ]]; then
            file=$(ls /c/buildroot/archives/*.7z)
            newfile=${file%.7z}-win7.7z
            mv $file $newfile
          fi

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.arch }} ${{ matrix.win32_winnt }}
          path: C:/buildroot/archives/*.7z

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            C:/buildroot/archives/*.7z
